import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/page/footer";
import Navbar from "@/components/page/navbar";

export const metadata = {
  title: "Résidence Eden Marrakech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <main>
          <Navbar/>
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}
